name: CI/CD Frontend CICD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, vps, kubernetes]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build frontend-cicd image
        run: |
          docker build -t frontend-cicd:latest ./frontend-cicd

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-cicd-deployment.yaml
          kubectl rollout status deployment/frontend-cicd
